{
    "docs": "https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/import.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test import --python 3.6` [[explain](https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/import.html)] failed with 1 error:", 
            "output": "plugins/modules/netfoundry_info.py:58:0: traceback: ModuleNotFoundError: No module named 'netfoundry'"
        }
    ], 
    "verified": false
}
